# Generated by Django 3.2.3 on 2021-05-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'ordering': ['author_name'], 'verbose_name_plural': 'author'},
        ),
    ]
