# Generated by Django 3.2.3 on 2021-05-22 16:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('book_name', models.CharField(max_length=255, unique=True)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('authors', models.ManyToManyField(to='authors.Authors')),
                ('categories', models.ManyToManyField(to='categories.Categories')),
            ],
        ),
    ]
